import Link from "next/link";
import { notFound } from "next/navigation";
import PageShell from "../../../components/PageShell";
import Markdown from "../../../components/Markdown";
import { getPlanArticles, getPlanArticle } from "../../../lib/articles";
import { H2, PickBlock, EventList, InlineLink } from "../../../components/PickBits";
import { getPicks, picksByType, picksByFacet } from "../../../lib/picksServer";
import { getUpcomingEvents } from "../../../lib/eventsServer";
import { getCollection } from "../../../lib/collections";

// Content comes from the DB (Google Docs sync); re-fetch every 5 min so edits
// appear without a redeploy.
export const revalidate = 300;

// This slug is served by a dedicated rich, data-driven page (app/plan/<slug>/page.jsx), so it
// must not also be generated by the dynamic route or the build would see two routes for one path.
const OVERRIDDEN = new Set(["things-to-do-in-san-miguel-de-allende"]);

// Per-guide enrichment: below each article we weave in our real picks, live events, and links to
// the matching shortlists, so a static how-to becomes a specific, current, proprietary page.
// `blocks` each render a labelled group of picks; `events` shows the live calendar; `collections`
// surfaces related /guide shortlists. Guides not listed here just render their article.
const PLAN_EXTRAS = {
  "where-to-eat-in-san-miguel-de-allende": {
    heading: "The specific places we'd send you",
    blocks: [
      { label: "A few we vouch for", kind: "type", key: "rest", limit: 4 },
    ],
    collections: ["best-restaurants-in-san-miguel-de-allende", "best-mexican-restaurants-in-san-miguel-de-allende", "best-date-night-restaurants-in-san-miguel-de-allende", "best-coffee-shops-in-san-miguel-de-allende"],
  },
  "3-days-in-san-miguel-de-allende": {
    heading: "Book these into your three days",
    blocks: [
      { label: "For a meal", kind: "type", key: "rest", limit: 2 },
      { label: "For a rooftop drink", kind: "facet", key: "views", limit: 2 },
      { label: "For a slow reset", kind: "facet", key: "wellness", limit: 1 },
    ],
    events: true,
    collections: ["best-rooftop-bars-in-san-miguel-de-allende", "best-restaurants-in-san-miguel-de-allende"],
  },
  "best-day-trips-from-san-miguel-de-allende": {
    heading: "Before you head out of town",
    events: true,
    collections: ["best-restaurants-in-san-miguel-de-allende", "best-wellness-and-spas-in-san-miguel-de-allende"],
  },
  "where-to-stay-in-san-miguel-de-allende": {
    heading: "Once you've picked your neighborhood",
    collections: ["best-restaurants-in-san-miguel-de-allende", "best-rooftop-bars-in-san-miguel-de-allende", "best-coffee-shops-in-san-miguel-de-allende", "family-friendly-things-to-do-in-san-miguel-de-allende"],
  },
  "getting-to-and-around-san-miguel-de-allende": {
    heading: "Once you're on the ground",
    collections: ["best-restaurants-in-san-miguel-de-allende", "best-cafes-to-work-remotely-in-san-miguel-de-allende"],
  },
};

export async function generateStaticParams() {
  return (await getPlanArticles()).map((p) => ({ slug: p.slug })).filter((p) => !OVERRIDDEN.has(p.slug));
}

export async function generateMetadata({ params }) {
  const page = await getPlanArticle(params.slug);
  if (!page) return { title: "Not found | Vamos San Miguel" };
  return {
    title: `${page.title} | Vamos San Miguel`,
    description: page.description || undefined,
    alternates: { canonical: `/plan/${page.slug}` },
    openGraph: { title: page.title, description: page.description || undefined, type: "article" },
  };
}

function faqFrom(body) {
  const lines = body.replace(/\r\n/g, "\n").split("\n");
  const faqs = [];
  for (let i = 0; i < lines.length; i++) {
    const h = /^##\s+(.*\?)\s*$/.exec(lines[i]);
    if (!h) continue;
    let j = i + 1;
    while (j < lines.length && !lines[j].trim()) j++;
    const ans = [];
    while (j < lines.length && lines[j].trim() && !/^#{1,6}\s/.test(lines[j]) && !/^\s*([-*]|\d+\.)\s+/.test(lines[j])) { ans.push(lines[j].trim()); j++; }
    if (ans.length) faqs.push({ q: h[1], a: ans.join(" ").replace(/\*\*|\[|\]\([^)]*\)/g, "") });
  }
  return faqs;
}

// Fetch and assemble the enrichment for a guide (only what its config asks for).
async function buildExtras(slug) {
  const cfg = PLAN_EXTRAS[slug];
  if (!cfg) return null;
  const needsPicks = Array.isArray(cfg.blocks) && cfg.blocks.length;
  const [picks, events] = await Promise.all([
    needsPicks ? getPicks().catch(() => []) : Promise.resolve([]),
    cfg.events ? getUpcomingEvents(14).catch(() => []) : Promise.resolve([]),
  ]);
  const blocks = (cfg.blocks || []).map((b) => ({
    label: b.label,
    picks: b.kind === "facet" ? picksByFacet(picks, b.key, b.limit) : picksByType(picks, b.key, { limit: b.limit }),
  })).filter((b) => b.picks.length);
  const collections = (cfg.collections || []).map((s) => getCollection(s)).filter(Boolean);
  const weekEvents = events.slice(0, 4);
  if (!blocks.length && !weekEvents.length && !collections.length) return null;
  return { heading: cfg.heading, blocks, weekEvents, collections };
}

export default async function PlanGuide({ params }) {
  const [page, extras] = await Promise.all([getPlanArticle(params.slug), buildExtras(params.slug)]);
  if (!page) notFound();
  const faqs = faqFrom(page.body);

  const articleLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: page.title,
    description: page.description || undefined,
    inLanguage: "en",
    author: { "@type": "Organization", name: "Vamos San Miguel" },
    publisher: { "@type": "Organization", name: "Vamos San Miguel" },
    mainEntityOfPage: `/plan/${page.slug}`,
  };
  const faqLd = faqs.length ? {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })),
  } : null;

  return (
    <PageShell active="plan">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleLd) }} />
      {faqLd && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }} />}

      <p style={{ fontSize: 13.5, margin: "0 0 18px", color: "#6E604F" }}>
        <Link href="/plan" style={{ color: "#0D1B36", textDecoration: "none", fontWeight: 600 }}>← Plan your trip</Link>
      </p>

      <article><Markdown body={page.body} /></article>

      {extras && (
        <section style={{ marginTop: 10 }}>
          {extras.heading && <H2>{extras.heading}</H2>}
          {extras.blocks.map((b) => <PickBlock key={b.label} label={b.label} picks={b.picks} />)}

          {extras.weekEvents.length > 0 && (
            <>
              <p style={{ fontFamily: "ui-monospace, Menlo, monospace", fontSize: 12, fontWeight: 700, letterSpacing: ".1em", textTransform: "uppercase", color: "#B4791F", margin: "10px 0 8px" }}>On while you're here</p>
              <EventList events={extras.weekEvents} />
              <p style={{ fontSize: 14, margin: "2px 0 6px" }}><InlineLink href="/whats-on">See the full What's On calendar →</InlineLink></p>
            </>
          )}

          {extras.collections.length > 0 && (
            <div style={{ display: "grid", gap: 6, margin: "14px 0 4px" }}>
              {extras.collections.map((c) => (
                <Link key={c.slug} href={`/guide/${c.slug}`} style={{ fontSize: 14.5, fontWeight: 600, color: "#0D1B36", textDecoration: "none", padding: "7px 0", borderTop: "1px solid #E7DDCB" }}>
                  {c.h1} <span style={{ color: "#E06A63" }}>→</span>
                </Link>
              ))}
            </div>
          )}
        </section>
      )}

      <div style={{ marginTop: 34, padding: "16px 20px", background: "#FFFFFF", border: "1px solid #E7DDCB", borderRadius: 14 }}>
        <p style={{ margin: 0, fontSize: 14.5, color: "#6E604F", lineHeight: 1.5 }}>
          More trip planning in the <Link href="/plan" style={{ color: "#E06A63", fontWeight: 600, textDecoration: "none" }}>guides</Link>, or browse our <Link href="/" style={{ color: "#E06A63", fontWeight: 600, textDecoration: "none" }}>Local Picks and events</Link>.
        </p>
      </div>
    </PageShell>
  );
}
